spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa.database-platform: org.hibernate.dialect.H2Dialect
  
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 